export default [
  {
    title: "Planlama",
    icon: { icon: "tabler-calendar-time" },
    policyKey: "menu:planlama",
    children: [
      {
        title: "İş Emirleri - Tümü",
        to: "planlama-is-emirleri-tumu",
        icon: { icon: "tabler-list" },
        policyKey: "menu:planlama:is-emirleri-tumu",
        target: "_blank",
      },
      {
        title: "İş Emirleri - Master",
        to: "planlama-is-emirleri-master",
        icon: { icon: "tabler-list" },
        policyKey: "menu:planlama:is-emirleri-master",
        target: "_blank",
      },
      {
        title: "İş Emirleri - Kapanmışlar",
        to: "planlama-is-emirleri-kapanmislar",
        icon: { icon: "tabler-list" },
        policyKey: "menu:planlama:is-emirleri-kapanmislar",
        target: "_blank",
      },
      {
        title: "İş Emirleri - Montaj",
        to: "planlama-is-emirleri-montaj",
        icon: { icon: "tabler-list" },
        policyKey: "menu:planlama:is-emirleri-montaj",
        target: "_blank",
      },
      {
        title: "İş Emirleri - Mekanik",
        to: "planlama-is-emirleri-mekanik",
        icon: { icon: "tabler-list" },
        policyKey: "menu:planlama:is-emirleri-mekanik",
        target: "_blank",
      },
      {
        title: "Malzeme İhtiyaç (İstasyon)",
        to: "planlama-ihtiyac-listesi-istasyon",
        icon: { icon: "tabler-list" },
        policyKey: "menu:planlama:ihtiyac-istasyon",
        target: "_blank",
      },
      {
        title: "Malzeme İhtiyaç (Toplu)",
        to: "planlama-ihtiyac-listesi-toplu",
        icon: { icon: "tabler-list" },
        policyKey: "menu:planlama:ihtiyac-toplu",
        target: "_blank",
      },
      {
        title: "Kapasite Hesapla",
        to: "planlama-kapasite-hesapla",
        icon: { icon: "tabler-list" },
        policyKey: "menu:planlama:kapasite-hesapla",
        target: "_blank",
      },
      {
        title: "Ürün Ağacı Sorgula",
        to: "planlama-urun-agaci-sorgula",
        icon: { icon: "tabler-list-tree" },
        policyKey: "menu:planlama:urun-agaci-sorgula",
        target: "_blank",
      },
    ],
  },
];
