export default [
  {
    title: "Planlama",
    icon: { icon: "tabler-calendar-time" },
    action: "read",
    subject: ["planlama", "mekanik", "montaj"],
    children: [
      {
        title: "İş Emirleri - Tümü",
        to: "planlama-is-emirleri-tumu",
        icon: { icon: "tabler-list" },
        action: "read",
        subject: ["planlama"],
        target: "_blank",
      },
      {
        title: "İş Emirleri - Kapanmışlar",
        to: "planlama-is-emirleri-kapanmislar",
        icon: { icon: "tabler-list" },
        action: "read",
        subject: ["planlama"],
        target: '_blank',
      },
      {
        title: "İş Emirleri - Master",
        to: "planlama-is-emirleri-master",
        icon: { icon: "tabler-list" },
        action: "read",
        subject: ["planlama"],
        target: "_blank",
      },
      {
        title: "İş Emirleri - Montaj",
        to: "planlama-is-emirleri-montaj",
        icon: { icon: "tabler-list" },
        action: "read",
        subject: ["planlama", "montaj"],
        target: "_blank",
      },
      {
        title: "İş Emirleri - Mekanik",
        to: "planlama-is-emirleri-mekanik",
        icon: { icon: "tabler-list" },
        action: "read",
        subject: ["planlama", "mekanik"],
        target: "_blank",
      },
      {
        title: "Malzeme İhtiyaç (İstasyon)",
        to: "planlama-ihtiyac-listesi-istasyon",
        icon: { icon: "tabler-list" },
        action: "read",
        subject: ["planlama", "montaj"],
        target: '_blank',
      },
      {
        title: "Malzeme İhtiyaç (Toplu)",
        to: "planlama-ihtiyac-listesi-toplu",
        icon: { icon: "tabler-list" },
        action: "read",
        subject: ["planlama", "montaj"],
        target: '_blank',
      },
      {
        title: "Malzeme İhtiyaç (Test)",
        to: "planlama-ihtiyac-listesi-test",
        icon: { icon: "tabler-list" },
        action: "manage",
        subject: ["all"],
        target: '_blank',
      },
      {
        title: "Kapasite Hesapla",
        to: "planlama-kapasite-hesapla",
        icon: { icon: "tabler-list" },
        action: "create",
        subject: ["planlama"],
        target: "_blank",
      },
    ],
  },
];
